### ISSUE TITLE
[feature request] Allow users to pick their own shortcuts

### ISSUE THREAD

**Issue by corysimmons** [mohnish/rearrange-tabs#11]

**Comment by mohnish** [comment]
Hi, @corysimmons. Thanks for taking time to open this issue. This has been requested a couple of times in the past by multiple users. I think it's time that the extension supports this feature.

I'm going to be busy till early Jan 2017 and I'll start development work around that time. This will be part of the next release.

Thank you!

**Comment by corysimmons** [comment]
np. I'll probably be used to ctrl+arrow by then, but it'll be helpful for people coming from terminal to be able to shift around tabs like in iTerm. :D

**Comment by kocoten1992** [comment]
Aye, personally I would config <alt><shift>H for left, L for right (from vim world)

**Comment by unknownbreaker** [comment]
In the meantime, you can define your own shortcut from the extensions page.

1. Go to chrome://extensions/
2. Scroll to the very bottom of the page
3. Click on "Keyboard Shortcuts" in the bottom right corner.
4. Look for "Rearrange Tabs" in the pop up that appears.
5. Click on the fields that say "Not set" and make up some key presses to set it.

![image](https://cloud.githubusercontent.com/assets/6026454/20898075/f2a391ba-baf2-11e6-9407-a745f1005f49.png)

Of course, it would be way cooler to create an options menu in the extension, but this is just as good.

**Comment by mohnish** [comment]
@unknownbreaker This is actually perfect! As a workaround for now, I think this is a really good solution. Thank you.

**Comment by unknownbreaker** [comment]
Surely. I'd be happy to make a PR.

**Comment by unknownbreaker** [comment]
@mohnish PR: https://github.com/mohnish/rearrange-tabs/pull/13

**Comment by corysimmons** [comment]
I think this is a fine solution -- probably better than making the extension fatter with another place to config it. This can be closed in favor of the PR.

**Comment by mohnish** [comment]
@unknownbreaker I agree with @corysimmons. I'm going to close this out and take a look at your PR #13
