### ISSUE TITLE
Don't install functionality on Linux

### ISSUE THREAD

**Issue by isiahmeadows** [mohnish/rearrange-tabs#16]
Linux already natively has `Ctrl+Shift+PgUp`/etc. to do this very thing, and given that you can't selectively not sync extensions in Chrome, I feel it may be best to just detect and not add the listener on Linux.

(I only just started using this on Mac, BTW.)

**Comment by isiahmeadows** [comment]
ChromeOS might also have this, but I'm not sure.

**Comment by mohnish** [comment]
Hi @isiahmeadows,

Thanks for taking time to open an issue. I can probably scope this to just Mac and Windows, but, users using the extension on Linux would not be able to use the feature anymore. Users like to use similar shortcut keys and that would break for them if I remove the functionality on Linux.

In your case, you should be able to configure the shortcut for `Rearrange Tabs` to use `Ctrl+Shift+PgUp/PgDown`. That way, you don't have to worry about selectively syncing your extensions. Hope that helps.
