### ISSUE TITLE
Some keyboard shortcuts are not accepted

### ISSUE THREAD

**Issue by dimoschi** [mohnish/rearrange-tabs#17]
I tried to set `cmd+ctrl+[` for moving tab left and `cmd+ctrl+]` for moving tab right, and both were not accepted. Anything else that I tried was OK.

**Comment by mohnish** [comment]
That's weird. It could be that those shortcuts are related to some other task. I will take a look at what's up later. Thank you for bringing this up.

**Comment by mohnish** [comment]
@dimoschi sorry about the extremely late response. it seems like it's a chrome issue. it has nothing to do with the extension. i'm closing this issue since it has nothing to do with the extension.
