### ISSUE TITLE
Unable to assign shortcut for special characters

### ISSUE THREAD

**Issue by Raekkeri** [mohnish/rearrange-tabs#24]
Hello!

When attempting to reassign a shortcut, it's not possible to set characters like `[` or `]`. It would be fancy if shortcuts like `ctrl + shift + [` could be assigned (since moving between tabs already works with `cmd + shifg + [` etc).

**Comment by mohnish** [comment]
Hi @Raekkeri, those are the keys outside of what Google Chrome currently supports. Unfortunately, this is not related directly with the extension. The only alternative is to use a library for handling keyboard shortcuts and that’s outside the scope of this tiny extension. Thanks for using the extension and your interest. I appreciate it. But, regarding the issue itself, I’m afraid there isn’t much I can do.
