### ISSUE TITLE
Chrome 69 address bar bug

### ISSUE THREAD

**Issue by corysimmons** [mohnish/rearrange-tabs#27]
Highlight address bar.

`Alt/Option + Shift + <--` should do word selection stuff. Instead it now shifts tabs around.

Thanks for helpful extension. I use it all the time.

**Comment by mohnish** [comment]
@corysimmons I've noticed this just now. Thanks for raising this issue. It seems like something around the shortcuts changed in Chrome 69. The only thing I can currently think of is that Chrome probably has started considering the `default` key from the `manifest.json` file. That's the only place `Alt+Shift+<arrow>` key combination is used (for Mac). I'll try removing it and test it locally and test it. If that works, I'll ship it out as soon as I can. Once again, thanks for raising the issue and I'm glad you find the extension helpful. Cheers!

**Comment by corysimmons** [comment]
Wow, great maintainer! 🙌

**Comment by dutzi** [comment]
+1
Love this extension, btw

**Comment by Luqih** [comment]
I temporarily overridden the shortcut in chrome://extensions/shortcuts
Currently using: cmd + shift + left / cmd + shift + right

**Comment by mohnish** [comment]
I've noticed something weird in Chrome 70. For those who haven't overridden the default shortcut, when you hit `Shift+Alt+<arrow>` from the URL bar, followed by **just** the `Shift` key **or** **just** the `Alt` key, the browser actually highlights the text you want to highlight in the URL bar (It still moves your tab around as a side effect). I'm still not sure what would cause this behavior.

**Comment by emiljohansson** [comment]
This is not a fix, but for some reason, changing the second dropdown from "In Chrome" to "Global" solves the address bar issue.

**Comment by mohnish** [comment]
@emiljohansson that can be programatically done. I was actually looking into that option yesterday. I’ll implement it locally and see if it works. Thanks for your input.

**Comment by mohnish** [comment]
Ok, looks like `Global` option is not really the right path since the shortcut triggers the extension even when Chrome is not in focus. Here's the doc https://developer.chrome.com/extensions/commands#scope

**Comment by mohnish** [comment]
I've reached out to Chrome Dev team and I haven't received any response back.

During debugging and testing, I tried switching the shortcut keys for Mac from <kbd>Ctrl+Shift+Left/Right/Up/Down</kbd> to <kbd>Ctrl+CMD+Left/Right/Up/Down</kbd>. This worked like a charm.

### Pros

* This will fix the issue and since <kbd>Ctrl+CMD+Left/Right/Up/Down</kbd> is not used for editing text

### Cons

* Besides the fact that this will break the extension for the existing users, the existing users will also have to get used to the new shortcuts.

So, I'm trying to decide if the change is worth it.

**Comment by corysimmons** [comment]
Add those shortcuts and add a place in the extension to change the shortcut to whatever the user wants. In that area, link to this issue.

If anyone complains, carve their heart out with a spoon.

**Comment by mohnish** [comment]
Appreciate the feedback, @corysimmons!

I think I'll add a pop-up or something similar that shows up once the extension is updated. That way it'd be easier to let the existing users know of the change.

**Comment by FranklinYu** [comment]
> I've reached out to Chrome Dev team and I haven't received any response back.

Is there any public information about this? Did you create a bug report or something?

**Comment by johangithub** [comment]
This is still happening @mohnish.

**Comment by DaveAllbirds** [comment]
Still having this issue on OSX. I love this extension but can't use it with this bug.

**Comment by mohnish** [comment]
@DaveAllbirds Hi Dave! 👋 

You can always change the shortcut to CTRL+CMD+<arrow_key> to avoid this issue. Hope that helps, cheers!

**Comment by giray123** [comment]
I am also desperately waiting for a fix here. I have tried the other methods, nothing works seamlessly on Mac.

**Comment by mohnish** [comment]
Addressed in https://github.com/mohnish/rearrange-tabs/pull/52
