### ISSUE TITLE
Feature Request: Move tabs to previous/next window

### ISSUE THREAD

**Issue by Jon-Schneider** [mohnish/rearrange-tabs#31]
Feature Request: Move tabs to previous/next window

Edit: It looks like there is an outstanding PR for this feature: https://github.com/mohnish/rearrange-tabs/pull/25

**Comment by mohnish** [comment]
@Jon-Schneider Yes. I'm currently working on a rewrite to support a new functionality. I'll merge the PR in once that's done. Thanks for the interest in the extension.
