### ISSUE TITLE
option+shift+left/right moves tabs when search bar is focused

### ISSUE THREAD

**Issue by MiLeung** [mohnish/rearrange-tabs#33]
This makes highlighting the next word with shift+left/right arrows impossibru

**Comment by mohnish** [comment]
@MiLeung thanks for taking time to open this issue. this is a known issue as of Chrome 69, unfortunately.

the current work around is to configure the shortcuts to use `CMD+Ctrl+<arrows>`

duplicate of https://github.com/mohnish/rearrange-tabs/issues/27
