### ISSUE TITLE
Tab move doesn't cycle when a tab is moved to the rightmost end

### ISSUE THREAD

**Issue by mohnish** [mohnish/rearrange-tabs#4]
Currently, when the tab is moved to the first position (0) and gets moved left one more time, it goes to the last position (n). This is how the tab moves should work when moved to the rightmost end.

**Comment by avidenic** [comment]
I'll take a look at it.

**Comment by mohnish** [comment]
fixed in https://github.com/mohnish/rearrange-tabs/pull/9
