### ISSUE TITLE
Feature Request: Make shortcuts configurable

### ISSUE THREAD

**Issue by RavenHursT** [mohnish/rearrange-tabs#40]
Thanks so much for this awesome extension!  I'm amazed that the Google/Chromium teams _still_ haven't included this simple functionality.

Anyway. The _one_ thing that I think would make this perfect, would be to add an extension config view that allows for the shortcuts to be configurable.

For example, on OSX, instead of CTRL+SHIFT+[arrow] for the operations, I'd love to be able to use ⌘CMD+SHIFT+[arrow].

Again, thanks so much for this extension. It's already awesome!

**Comment by mohnish** [comment]
Hi @RavenHursT 👋 

Rearrange Tabs already supports this. You can read the instruction here on how to change the shortcuts: https://github.com/mohnish/rearrange-tabs#customize-shortcut

**Comment by RavenHursT** [comment]
That's flippin' awesome.

Sorry I missed that in the documentation, mah bad. 🤦‍♂️

Thanks again!

**Comment by mohnish** [comment]
@RavenHursT I just noticed something interesting. I think it is not quite obvious from the README or the Extension notes that the shortcuts can be configured. I've had a few users complain about the default shortcut. I will try to come up with changes to make this extremely obvious. Thanks for bring this up. It opened up a good opportunity.

**Comment by RavenHursT** [comment]
That's awesome to hear @mohnish !  

Such a breath of fresh air to see a maintainer looking to make it _easier_ for consumers to use their tools, rather than just screaming "RTFM!" and mashing the `close` button on issues.

Bravo.
