### ISSUE TITLE
Include info about configuring shortcut keys

### ISSUE THREAD

**Issue by mohnish** [mohnish/rearrange-tabs#41]
Right now, it doesn't look like it's obvious that you can configure the keyboard shortcuts to invoke the extension. Will come up with a way to make it obvious. 

Reference: https://github.com/mohnish/rearrange-tabs/issues/40

**Comment by mohnish** [comment]
Probably even change the default shortcut? Something to think about in order to avoid the confusion.

**Comment by tnorthcutt** [comment]
Is there a reason that the shortcuts must require one of control, command, or alt (on macOS)? I think I'd like to set a shortcut that doesn't necessarily use one of those, but not sure if that's a Chrome restriction rather than a UX choice you made.

**Comment by mohnish** [comment]
@tnorthcutt That's correct. [Chrome has a requirement to use one of 'em in the extension shortcuts](https://developer.chrome.com/docs/extensions/reference/commands/#:~:text=Extension%20command%20shortcuts%20must%20include%20either%20Ctrl%20or%20Alt.).

**Comment by tnorthcutt** [comment]
@mohnish makes sense, thank you!

**Comment by mohnish** [comment]
Addressed in https://github.com/mohnish/rearrange-tabs/pull/52
