### ISSUE TITLE
New tabs move when trying to select text

### ISSUE THREAD

**Issue by or9or10** [mohnish/rearrange-tabs#42]
Trying to select text in a new tab URL window with the shift-option-arrow keys shortcut activates the Rearrange Tabs extension.

![image](https://user-images.githubusercontent.com/52925919/116816142-6f2bf680-ab69-11eb-8f68-665f599413f9.png)

**Comment by mohnish** [comment]
Hi @or9or10! This is a known issue ATM. It's a Chromium related issue from what I know. The current workaround is to re-configure your extension's keyboard shortcuts. Here's how you can do it: https://github.com/mohnish/rearrange-tabs#customize-shortcut
