### ISSUE TITLE
Add a shortcut to handle tabs group

### ISSUE THREAD

**Issue by ymentha14** [mohnish/rearrange-tabs#43]
Hi there,

That would be awesome to have a way to create/manage groups of tabs using a shortcut in addition to the existing (super useful!) features. For instance, one shortcut to create a new group and one other tomove the current tab to a group lying on the right left.

**Comment by mohnish** [comment]
Hi @ymentha14, sorry about the delay in my response.

I like the idea, but I'm not sure if Chrome supports this functionality via their Extension APIs. However, I will definitely look into it and I have had multiple people request this feature.

For now, I will close this issue and later create a milestone to reflect any research or work around it. Thanks for being a user and appreciate you taking time to suggest new useful features that'd benefit the wider community as well. Cheers!
