### ISSUE TITLE
For some reason, Google Chrome has frequent crashes when this plugin is enabled

### ISSUE THREAD

**Issue by benwoodward** [mohnish/rearrange-tabs#48]
I cannot pin down exactly why though, not sure how to debug. 

Chrome version: Version 99.0.4844.51 (Official Build) (x86_64)
MacOS version: 11.5.2 (20G95)
Shortcuts used: option-H, option-L

I've systematically removed all extensions, and added them back one by one and it's always this plugin that causes crashes.

The crashes sometimes occur without the extension, but as soon as I reenable it they come back with a lot of frequency (few times a day). 

Wondering whether there's a bug in Chrome JS engine and this extension happens to use an API that triggers the bug. Super strange as this extension is so simple.

**Comment by mohnish** [comment]
@benwoodward Thanks for the report! This is very interesting as I've never had a report saying that this extension caused a browser crash. Does it crash with the default shortcuts too?

> Wondering whether there's a bug in Chrome JS engine and this extension happens to use an API that triggers the bug

I wouldn't rule this out. Maybe even https://github.com/mohnish/rearrange-tabs/issues/27 is related to it. It'd definitely be a good avenue to explore with a fresh perspective.

**Comment by benwoodward** [comment]
I'll try using a different shortcut and see if that makes a difference. 

One other theory I have is that the extension is somehow conflicting with another extension. 

Not expecting you to be able to solve this, just figured I should log the issue in case anyone else experiences it too.

**Comment by mohnish** [comment]
Makes sense. Logging this would definitely be useful to track it for later. Thanks!

**Comment by mohnish** [comment]
Hey @benwoodward, I've [rewritten the extension](https://github.com/mohnish/rearrange-tabs/pull/52) to support Manifest v3. I will be pushing the update out to the Webstore today. Once your extension is updated, you should see a new tab with the details of the update. LMK if the issue still persists after the update to 3.0.0! Once again, thank you for taking time to actually investigate this issue. Appreciate your help with that :)

**Comment by benwoodward** [comment]
fantastic! I'll test it out. thanks.

**Comment by akirataguchi115** [comment]
@benwoodward any updates on this?

**Comment by benwoodward** [comment]
> @benwoodward any updates on this?

From basic testing it's working fine in Chrome, haven't experienced a crash yet.

**Comment by mohnish** [comment]
@benwoodward That's great to hear. I will close this one out then. We can create a new one or re-open this one if it arises again. Thanks again for taking time to test this.
