### ISSUE TITLE
After 3.0.0 - stopped working in linux

### ISSUE THREAD

**Issue by robcxyz** [mohnish/rearrange-tabs#57]
Per title, ever since the extension was updated on Feb 17th, this stopped working in linux. Used to work with `ctrl + alt + left|right arrow` and now it doesn't. 

Fixed by customizing the extension in chrome://extensions/shortcuts per README but odd that it doesn't work by default.

**Comment by mohnish** [comment]
Hi @robcxyz 👋 

Unfortunately, that's what seems to be the case when the default combination is changed in Chrome extensions programmatically. I wish it weren't that way, but it is. Sorry that the change wiped your default key combination.

Another issue for reference: https://github.com/mohnish/rearrange-tabs/issues/54
