### ISSUE TITLE
Tabs no longer wrap to beginning when at the end position

### ISSUE THREAD

**Issue by dannypernik** [mohnish/rearrange-tabs#63]
Perhaps I'm imagining things, but am I correct in thinking that when a tab is in the last position and you move it right, it should move to the beginning of the tab list? Conversely, when the tab is at the beginning and you move it left, it should move to the end?

Currently this is not happening. Thanks for any help you can provide.

**Comment by mohnish** [comment]
Hi @dannypernik! This was intentional. I've introduced the new "move to front" and "move to back" commands. You can use them to quickly move tabs to front and back. They're more efficient and you'll quickly get used to those. Try 'em out.

**Comment by dannypernik** [comment]
Gotcha. I knew about the move to front and move to back, but I liked the option of wrapping tabs too. All good though :)
