### ISSUE TITLE
Move multiple tabs

### ISSUE THREAD

**Issue by avidenic** [mohnish/rearrange-tabs#8]
When selecting tabs with ctrl (on windows), only the last selected tabs is moved, not all that were selected. 

Please add an option to move several tabs at once.

**Comment by mohnish** [comment]
Hi, thanks for opening an issue. Could you explain the issue in more detail, please :)

Thank you!

**Comment by avidenic** [comment]
Hello,

Chrome has an option to select multiple tabs by holding down ctrl key (probably command on OS X) and clicking on them. One can than drag all selected tabs left or right by clicking on any of them, holding the left mouse button and then dragging. But if I use shortcut (alt + shift + arrow) only the last selected tab is moved. Would be cool if shortcut mimics the default mouse behavior. 

I hope I was clear enough. 

Regards.

**Comment by mohnish** [comment]
@avidenic Thanks for explaining it in detail. Wow, I wasn't aware of such an option. It definitely seems cool. I will take a stab at it over the weekend.

Cheers!

**Comment by avidenic** [comment]
@mohnish Great! If you don't have time, I might take a look at it in next few weeks. It is not super urgent =)

**Comment by mohnish** [comment]
Sure, @avidenic! That'd be awesome! I tried getting to it but I didn't have the time and hence the delay. If you want to start working on it, please feel free. I'd really appreciate it.

**Comment by avidenic** [comment]
Hey, I've started on this issue, should be complete today. Will open a pull request when it is done.

**Comment by mohnish** [comment]
@avidenic this is awesome. would love to go through the PR. thank you for the effort.

**Comment by mohnish** [comment]
fixed in https://github.com/mohnish/rearrange-tabs/pull/9
